// @ts-check
/**
 * Every string the add-on shows a player.
 *
 * Nothing user-facing is written inline any more: a screen or a command says
 * `TEXT.menu.something`, and the wording lives here. That makes the whole
 * player-visible surface auditable in one file, stops the same refusal being
 * worded two ways in two layers, and is the groundwork translation needs.
 *
 * Two conventions:
 *
 *   - Formatting codes stay **inside** the strings. Colour is presentation and
 *     belongs with the wording, not scattered across the call sites.
 *   - A string with values in it is a function taking them in order, so a
 *     translation can move them around the sentence.
 *
 * Still ahead: `RawMessage` with `.lang` keys, which is what Minecraft wants
 * for real localisation. That is a larger change — it alters the type of every
 * message and form label — and this catalogue is the step that makes it
 * tractable rather than a rewrite.
 */

import { C, LEADER_ROLE } from './config.js';

/**
 * A value interpolated into a message: a name, a count, a clan.
 *
 * @typedef {string | number} Value
 */

export const TEXT = {
  board: {
    warKills: `War Kills`,
  },
  status: {
    chatTagsActivePlayerChatnameprefix: `chat tags active (Player.chatNamePrefix)`,
    chatTagsActiveChatsendFallback: `chat tags active (chatSend fallback)`,
    chatSupportNotYetDetermined: `chat support not yet determined`,
    chatTagsUnavailableEnableThe: `chat tags unavailable; enable the "Beta APIs" experiment`,
  },
  announce: {
    hasBeenFoundedBy: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.aqua}${a0}${C.yellow} has been founded by ${C.white}${a1}${C.yellow}.`,
    wasRemovedFrom: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.white}${a0}${C.gray} was removed from ${C.aqua}${a1}${C.gray}.`,
    hasBeenDisbanded: (/** @type {Value} */ a0) => `${C.aqua}${a0}${C.red} has been disbanded.`,
    hasBeenPromotedFromAn: (/** @type {Value} */ a0) => `${C.aqua}${a0}${C.gold} has been promoted from an outpost to a full clan.`,
    hasDeclaredWarOnAwaiting: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.red}${a0} has declared war on ${a1}${C.gray}, awaiting their answer.`,
    isNowAtWarWith: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.red}${a0} is now at war with ${a1}${C.red}!`,
    warHasBrokenOutBetween: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.red}War has broken out between ${a0} and ${a1}!`,
    hasSurrenderedTo: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gold}${a0} has surrendered to ${a1}.`,
    forfeitedItsWarWith: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gold}${a0} forfeited its war with ${a1}.`,
    andHaveMadePeace: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gold}${a0} and ${a1} have made peace.`,
    theWarBetweenAndWas: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}The war between ${a0} and ${a1} was annulled.`,
    theWarBetweenAndIs: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gold}The war between ${a0} and ${a1} is over.`,
  },
  /**
   * Short pieces built into longer lines: a status word, a fallback for a name
   * that no longer resolves, a placeholder option in a dropdown.
   *
   * They read as scraps rather than sentences, which is exactly why they were
   * easy to leave scattered — and exactly why a translator needs them here.
   */
  /**
   * Names for the symbol palette in `config.js`, keyed by its ids. A dropdown
   * of bare glyphs is unreadable at a glance, so each is shown as the glyph
   * beside its name.
   */
  symbol: {
    star: `Star`,
    starOutline: `Star Outline`,
    sparkle: `Sparkle`,
    sparkleOutline: `Sparkle Outline`,
    burst: `Burst`,
    asterisk: `Asterisk`,
    crown: `Crown`,
    swords: `Crossed Swords`,
    hammers: `Hammer and Pick`,
    flag: `Flag`,
    flagOutline: `Flag Outline`,
    skull: `Skull`,
    peace: `Peace`,
    balance: `Balance`,
    node: `Node`,
    cross: `Cross`,
    crossOrnate: `Ornate Cross`,
    dagger: `Dagger`,
    doubleDagger: `Double Dagger`,
    diamond: `Diamond`,
    diamondOutline: `Diamond Outline`,
    circle: `Circle`,
    circleOutline: `Circle Outline`,
    square: `Square`,
    squareOutline: `Square Outline`,
    triangleUp: `Triangle Up`,
    triangleDown: `Triangle Down`,
    spade: `Spade`,
    club: `Club`,
    heart: `Heart`,
    suitDiamond: `Diamond Suit`,
  },
  /**
   * Names for the colour palette in `config.js`, keyed by its ids. Kept apart
   * from the codes because the code is a fact about Minecraft and the name is
   * a word in a language.
   */
  color: {
    white: `White`,
    gray: `Gray`,
    darkGray: `Dark Gray`,
    black: `Black`,
    blue: `Blue`,
    aqua: `Aqua`,
    green: `Green`,
    yellow: `Yellow`,
    gold: `Gold`,
    red: `Red`,
    pink: `Pink`,
    purple: `Purple`,
    darkBlue: `Dark Blue`,
    darkAqua: `Dark Aqua`,
    darkGreen: `Dark Green`,
    darkRed: `Dark Red`,
    minecoin: `Minecoin`,
    quartz: `Quartz`,
    iron: `Iron`,
    netherite: `Netherite`,
    redstone: `Redstone`,
    copper: `Copper`,
    goldOre: `Gold Ore`,
    emerald: `Emerald`,
    diamond: `Diamond`,
    lapis: `Lapis`,
    amethyst: `Amethyst`,
    resin: `Resin`,
  },
  fragment: {
    noRole: `none`,
    noClan: `no clan`,
    noStaffRole: `no staff role`,
    online: `online`,
    offline: `offline`,
    lostClan: `a lost clan`,
    unknownPlayer: `Unknown player`,
    unknownDate: `unknown`,
    notMarked: `not marked`,
    warPending: `awaiting answer`,
    warActive: `active`,
    won: `Won`,
    lost: `Lost`,
    drawn: `Drawn`,
    wonLower: `won`,
    lostLower: `lost`,
    drawnLower: `drawn`,
    pickNoRole: `(no role)`,
    pickNewRole: `(type a new role below)`,
    pickNoStaffRole: `(no staff role)`,
    pickUnattributed: `(unattributed adjustment)`,
  },
  /**
   * Refusals more than one layer says. A command and the screen behind it
   * refuse the same things, and two copies of the same sentence drift.
   */
  common: {
    notInAClan: `You are not in a clan.`,
    notInAClanCreate: `You are not in a clan. Use /clan:create to start one.`,
    clanGone: `That clan no longer exists.`,
    inventoryFull: `Your inventory is full.`,
    notClanManager: `You do not have clan-management access.`,
    notReviewer: `You cannot review clan requests.`,
    notAdminPurge: `Only admins can purge players.`,
    notAdminSettings: `Only admins can change settings.`,
    notAdminDisplay: `Only admins can change display settings.`,
    notAdminStaffRoles: `Only admins can manage staff roles.`,
    notPeacefulAssigner: `You cannot assign the Peaceful role.`,
    notWarAdjuster: `You cannot adjust war kills.`,
    notClanLeaderRename: `Only the Leader can rename the clan.`,
    notClanLeaderInvite: `Only the clan owner can invite players.`,
    notClanLeaderRoles: `Only the clan owner can assign roles.`,
    offlineUseMenu: `No such player online. Use /clan:menu for offline members.`,
    offlineUseMenuInvite: `No such player online. Use /clan:menu to invite offline players.`,
    offlineUseManage: `No such player online. Use /clan:manage for offline players.`,
  },
validate: {
    clanNamesMustBeCharacters: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Clan names must be ${a0}-${a1} characters.`,
    clanNamesMayOnlyUse: `Clan names may only use letters, numbers, spaces, _ and -.`,
    roleNamesMustBeCharacters: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Role names must be ${a0}-${a1} characters.`,
    roleNamesMayOnlyUse: `Role names may only use letters, numbers, spaces, _ and -.`,
    isReservedForTheClan: `"${LEADER_ROLE}" is reserved for the clan owner.`,
    staffRoleNamesMustBe: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Staff role names must be ${a0}-${a1} characters.`,
    staffRoleNamesMayOnly: `Staff role names may only use letters, numbers, spaces, _ and -.`,
    staffTagsMustBeCharacters: (/** @type {Value} */ a0) => `Staff tags must be 1-${a0} characters.`,
  },
clan: {
    thatClanNoLongerExists: `That clan no longer exists.`,
    thatIsNotAColour: `That is not a colour this add-on offers.`,
    isAlreadyAFullClan: (/** @type {Value} */ a0) => `${a0} is already a full clan.`,
    youAreAlreadyInA: `You are already in a clan. Leave or disband it first.`,
    aClanNamedAlreadyExists: (/** @type {Value} */ a0) => `A clan named "${a0}" already exists.`,
    isAlreadyIn: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} is already in ${a1}.`,
    isAlreadyInAnotherClan: (/** @type {Value} */ a0) => `${a0} is already in another clan.`,
    isFullMembers: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} is full (${a1} members).`,
    thatPlayerIsNotIn: `That player is not in this clan.`,
    ownsTransferLeadershipOrDisband: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} owns ${a1}. Transfer leadership or disband the clan instead.`,
    theClanOwnerAlwaysHolds: `The clan owner always holds "${LEADER_ROLE}".`,
    isAlreadyARoleIn: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `"${a0}" is already a role in ${a1}.`,
    isNotARoleIn: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `"${a0}" is not a role in ${a1}.`,
    alreadyLeads: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} already leads ${a1}.`,
  },
invite: {
    youCannotInviteYourself: `You cannot invite yourself.`,
    isAlreadyIn: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} is already in ${a1}.`,
    isAlreadyInAnotherClan: (/** @type {Value} */ a0) => `${a0} is already in another clan.`,
    isFullMembers: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} is full (${a1} members).`,
    alreadyHasAPendingInvite: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} already has a pending invite to ${a1}.`,
    thatInviteIsNoLonger: `That invite is no longer valid.`,
    youAreAlreadyInA: `You are already in a clan. Leave it before joining another.`,
    noLongerExists: (/** @type {Value} */ a0) => `${a0} no longer exists.`,
  },
request: {
    onlyTheLeaderCanRename: `Only the Leader can rename the clan.`,
    isAlreadyCalledThat: (/** @type {Value} */ a0) => `${a0} is already called that.`,
    alreadyHasARenamePending: (/** @type {Value} */ a0) => `${a0} already has a rename pending.`,
    theRequestQueueIsFull: `The request queue is full. Ask an admin to review it.`,
    aClanNamedAlreadyExists: (/** @type {Value} */ a0) => `A clan named "${a0}" already exists.`,
    isAlreadyRequestedBy: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `"${a0}" is already requested by ${a1}.`,
    youAreAlreadyInA: `You are already in a clan.`,
    theClanRequestQueueIs: `The clan request queue is full. Ask an admin to review it.`,
    isAlreadyAFullClan: (/** @type {Value} */ a0) => `${a0} is already a full clan.`,
    onlyTheLeaderCanRequest: `Only the Leader can request promotion.`,
    needsMembersToRequestPromotion: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${a0} needs ${a1} members to request promotion, and has ${a2}.`,
    alreadyHasAPromotionRequest: (/** @type {Value} */ a0) => `${a0} already has a promotion request pending.`,
    thatRequestNoLongerExists: `That request no longer exists.`,
    noLongerExistsTheRequest: (/** @type {Value} */ a0) => `${a0} no longer exists. The request was dropped.`,
    hasFallenBelowMembersAnd: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} has fallen below ${a1} members and cannot be promoted yet.`,
    hasJoinedAClanSince: (/** @type {Value} */ a0) => `${a0} has joined a clan since requesting. The request was dropped.`,
  },
war: {
    aClanCannotGoTo: `A clan cannot go to war with itself.`,
    isAnOutpostOutpostsCannot: (/** @type {Value} */ a0) => `${a0} is an outpost. Outposts cannot declare war.`,
    isAnOutpostAndCannot: (/** @type {Value} */ a0) => `${a0} is an outpost and cannot be drawn into a war.`,
    isAlreadyAtWarWith: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} is already at war with ${a1}.`,
    alreadyHoldsTheMaximumOf: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} already holds the maximum of ${a1} war(s).`,
    thatWarNoLongerExists: `That war no longer exists.`,
    thatDeclarationIsNoLonger: `That declaration is no longer awaiting a response.`,
    thatDeclarationNoLongerExists: `That declaration no longer exists.`,
    thatWarHasAlreadyBegun: `That war has already begun; surrender or agree peace instead.`,
    onlyTheClanThatDeclared: `Only the clan that declared can withdraw it.`,
    thatWarHasNotBegun: `That war has not begun, so there is nothing to surrender.`,
    thatClanIsNotIn: `That clan is not in this war.`,
    thatWarIsNotBeing: `That war is not being fought.`,
    youHaveAlreadyOfferedPeace: `You have already offered peace. It is on them to answer.`,
    youHaveNoPeaceOffer: `You have no peace offer standing.`,
    thatWarHasAlreadyEnded: `That war has already ended.`,
    enterANonZeroWhole: `Enter a non-zero whole number.`,
    didNotFightForIn: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} did not fight for ${a1} in this war.`,
  },
book: {
    peaceWasAgreed: `Peace was agreed.`,
    thisWarIsUnfinished: `This war is unfinished.`,
    noKillsRecorded: `No kills recorded.`,
    totalKills: `Total kills`,
    correctionsNeed: `corrections need`,
    aFreshCopy: `a fresh copy.`,
    morePageSOmittedThis: (/** @type {Value} */ a0) => `+${a0} more page(s)\nomitted: this war\nis too large to\nprint in full.`,
    hasNoBookComponent: (/** @type {Value} */ a0) => `${a0} has no book component`,
    thatWarIsStillBeing: `That war is still being fought.`,
    yourInventoryIsFull: `Your inventory is full.`,
    thatRecordCouldNotBe: `That record could not be printed.`,
  },
staffRole: {
    aStaffRoleNamedAlready: (/** @type {Value} */ a0) => `A staff role named "${a0}" already exists.`,
    thatStaffRoleNoLonger: `That staff role no longer exists.`,
    isABuiltInRole: (/** @type {Value} */ a0) => `"${a0}" is a built-in role and cannot be deleted.`,
  },
join: {
    youHavePendingClanInvite: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.yellow}You have ${a0} pending clan invite(s): ${C.aqua}${a1}
${C.gray}Respond with ${C.white}/clan:accept${C.gray}, or use your Clan Ledger.`,
    clanRequestSAwaitingReview: (/** @type {Value} */ a0) => `${C.yellow}${a0} clan request(s) awaiting review.
${C.gray}Open ${C.white}/clan:requests${C.gray} to handle them.`,
    killed: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3, /** @type {Value} */ a4, /** @type {Value} */ a5, /** @type {Value} */ a6, /** @type {Value} */ a7) => `${C.red}${a0}${C.gray} killed ${C.red}${a1}${C.gray} — ${C.white}${a2} ${C.yellow}${a3}${C.darkGray} - ${C.yellow}${a4} ${C.white}${a5}${C.darkGray} (${a6}: ${a7})`,
    welcomeBackYouAre: (/** @type {Value} */ a0) => `${C.gray}Welcome back. You are ${a0}${C.gray}.`,
    yourClanRequestForIs: (/** @type {Value} */ a0) => `${C.gray}Your clan request for ${C.aqua}${a0}${C.gray} is still awaiting review.`,
  },
cmd: {
    thisCommandCanOnlyBe: `This command can only be run by a player.`,
    yourRole: `Your role`,
    openTheClanMenu: `Open the clan menu`,
    getAClanLedger: `Get a Clan Ledger`,
    getAWarMapBlock: `Get a War Map block to place`,
    openTheWarScreen: `Open the war screen`,
    listEveryActiveWar: `List every active war`,
    listTheEndedWarsOf: `List the ended wars of a clan`,
    printTheRecordBookFor: `Print the record book for an ended war`,
    requestPromotionFromOutpostTo: `Request promotion from outpost to full clan`,
    createAClanOrRequest: `Create a clan, or request one when approval is required; admins may name a player to create it for`,
    inviteAPlayerToYour: `Invite a player to your clan`,
    listYourPendingClanInvites: `List your pending clan invites`,
    acceptAPendingClanInvite: `Accept a pending clan invite`,
    declineAPendingClanInvite: `Decline a pending clan invite`,
    removeAMemberFromA: `Remove a member from a clan`,
    assignAClanRoleTo: `Assign a clan role to a member`,
    renameYourClanOrRequest: `Rename your clan, or request a new name`,
    leaveYourClan: `Leave your clan`,
    deleteYourClan: `Delete your clan`,
    showClanDetails: `Show clan details`,
    listEveryClan: `List every clan`,
    transferTheLeaderRoleTo: `Transfer the Leader role to another member`,
    openTheClanManagementMenu: `Open the clan management menu`,
    reviewPendingClanCreationRequests: `Review pending clan creation requests`,
    manageStaffRoles: `Manage staff roles`,
    changeApprovalNotificationAndPolling: `Change approval, notification and polling settings`,
    changeHowClanAndSystem: `Change how clan and system identity is displayed`,
    grantOrClearThePeaceful: `Grant or clear the Peaceful role`,
    removeAPlayerFromThe: `Remove a player from the clan system entirely`,
    adjustWarKillsOptionallyFor: `Adjust war kills, optionally for one member`,
    showAddOnDiagnostics: `Show add-on diagnostics`,
    reviewNoticeCreate: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.yellow}${a0} requested the clan ${C.aqua}${a1}${C.yellow}.\n${C.gray}Review with ${C.white}/clan:requests${C.gray}.`,
    reviewNoticePromote: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.yellow}${a0} asked to promote ${C.aqua}${a1}${C.yellow} to a full clan.\n${C.gray}Review with ${C.white}/clan:requests${C.gray}.`,
    reviewNoticeRename: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${C.yellow}${a0} asked to rename ${C.aqua}${a1}${C.yellow} to ${C.aqua}${a2}${C.yellow}.\n${C.gray}Review with ${C.white}/clan:requests${C.gray}.`,
    youHavePendingInvitesName: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `You have ${a0} pending invites. Name one: ${a1}`,
    requestedTheClanAnAdmin: (/** @type {Value} */ a0) => `${C.yellow}Requested the clan ${C.aqua}${a0}${C.yellow}.
${C.gray}An admin will review it. You will be told either way.`,
    invitedYouToJoinUse: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.yellow}${a0} invited you to join ${C.aqua}${a1}${C.yellow}.
${C.gray}Use ${C.white}/clan:accept${C.gray} or ${C.white}/clan:deny${C.gray}, or open ${C.white}/clan:menu${C.gray}.`,
    youOwnTransferLeadershipWith: (/** @type {Value} */ a0) => `You own ${a0}. Transfer leadership with /clan:transfer, or delete it with /clan:disband.`,
    youAreNotInA: `${C.gray}You are not in a clan.`,
    isNotInAClan2: (/** @type {Value} */ a0) => `${C.gray}${a0} is not in a clan.`,
    memberS3: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3, /** @type {Value} */ a4) => `${C.aqua}${a0}${C.gray} — ${a1} member(s)
${C.gray}${a2}: ${C.white}${a3}
${a4}`,
    clansStatusChatClansStaff: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${C.gray}Clans status
${C.gray}Chat: ${C.white}${a0}
${C.gray}Clans: ${C.white}${a1}
${C.gray}Staff roles: ${C.white}${a2}`,
    nowHasKillSTotals: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3) => `${a0} now has ${a1} kill(s); ${a2} totals ${a3}.`,
    nowTotalsWarKillS: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} now totals ${a1} war kill(s), as an adjustment.`,
    thereIsNoClanNamed2: (/** @type {Value} */ a0) => `There is no clan named "${a0}".`,
    hasWarsNumberedAgainstName: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3, /** @type {Value} */ a4, /** @type {Value} */ a5) => `${a0} has ${a1} wars numbered ${a2}, against ${a3}. Name one: /clan:warbook ${a4} ${a5} <opponent>`,
    warHistoryPrintOneWith: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gold}${a0} war history:
${a1}
${C.gray}Print one with ${C.white}/clan:warbook${C.gray}.`,
    somethingWentWrongRunningThat: `Something went wrong running that command.`,
    clanCreatedYouAreIts: (/** @type {Value} */ a0) => `Clan "${a0}" created. You are its ${LEADER_ROLE}.`,
    onlyAdminsCreateForOthers: `Only admins can create a clan on behalf of another player.`,
    createdTheOutpostFor: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Outpost "${a0}" created for ${a1}. They are its ${LEADER_ROLE}.`,
    anAdminCreatedTheOutpost: (/** @type {Value} */ a0) => `${C.green}An admin created the ${C.gray}outpost ${C.aqua}${a0}${C.green} for you. You are its ${LEADER_ROLE}.`,
    hereIsYourClanMenu: `Here is your Clan Ledger. Use it to open the menu.`,
    youAlreadyHaveAClanMenu: `You already have a Clan Ledger in your inventory.`,
    invitedTo: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Invited ${a0} to ${a1}.`,
    youHaveNoPendingClan: `${C.gray}You have no pending clan invites.`,
    pendingInvitesAcceptWithClan: (/** @type {Value} */ a0) => `${C.yellow}Pending invites:
${a0}
${C.gray}Accept with /clan:accept <clan>.`,
    youHaveNoPendingClan2: `You have no pending clan invites.`,
    youHaveNoPendingInvite: (/** @type {Value} */ a0) => `You have no pending invite from "${a0}".`,
    youJoined: (/** @type {Value} */ a0) => `You joined ${a0}.`,
    joinedTheClan: (/** @type {Value} */ a0) => `${C.green}${a0} joined the clan.`,
    declinedTheInviteFrom: (/** @type {Value} */ a0) => `${C.gray}Declined the invite from ${a0}.`,
    declinedYourInviteTo: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}${a0} declined your invite to ${a1}.`,
    isNotInAClan: (/** @type {Value} */ a0) => `${a0} is not in a clan.`,
    youCannotRemoveMembersFrom: (/** @type {Value} */ a0) => `You cannot remove members from ${a0}.`,
    removedFrom: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Removed ${a0} from ${a1}.`,
    youWereRemovedFrom: (/** @type {Value} */ a0) => `${C.red}You were removed from ${a0}.`,
    wasRemovedFromTheClan: (/** @type {Value} */ a0) => `${C.gray}${a0} was removed from the clan.`,
    clearedSRole: (/** @type {Value} */ a0) => `Cleared ${a0}'s role.`,
    yourRoleInWasCleared: (/** @type {Value} */ a0) => `${C.gray}Your role in ${a0} was cleared.`,
    isNow: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} is now ${a1}.`,
    youAreNowIn: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.green}You are now ${a0} in ${a1}.`,
    youLeft: (/** @type {Value} */ a0) => `${C.gray}You left ${a0}.`,
    leftTheClan: (/** @type {Value} */ a0) => `${C.gray}${a0} left the clan.`,
    onlyTheClanOwnerCan: `Only the clan owner can disband this clan.`,
    wasDisbanded: (/** @type {Value} */ a0) => `${C.red}${a0} was disbanded.`,
    disbanded: (/** @type {Value} */ a0) => `Disbanded ${a0}.`,
    youCannotChangeLeadershipOf: (/** @type {Value} */ a0) => `You cannot change leadership of ${a0}.`,
    nowLeads: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} now leads ${a1}.`,
    isNowTheOf: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.yellow}${a0} is now the ${LEADER_ROLE} of ${a1}.`,
    noClansExistYetCreate: `${C.gray}No clans exist yet. Create one with /clan:create.`,
    clans: (/** @type {Value} */ a0) => `${C.yellow}Clans:
${a0}`,
    onlyAdminsCanViewAdd: `Only admins can view add-on status.`,
    requestedTheNameAwaitingReview: (/** @type {Value} */ a0) => `${C.yellow}Requested the name ${C.aqua}${a0}${C.yellow}. Awaiting review.`,
    noWarsAreBeingFought: `${C.gray}No wars are being fought.`,
    activeWars: (/** @type {Value} */ a0) => `${C.red}Active wars:
${a0}`,
    onlyTheClanLeaderCan: `Only the clan Leader can get a War Map.`,
    hereIsYourWarMap: `Here is your War Map. Place it and interact with it to manage wars.`,
    thereIsNoClanNamed: (/** @type {Value} */ a0) => `There is no clan named "${a0}".`,
    isNotInAnActive: (/** @type {Value} */ a0) => `${a0} is not in an active war.`,
    isInWarsUseThe: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} is in ${a1} wars. Use the War Map to pick one.`,
    hasFoughtNoWarsTo: (/** @type {Value} */ a0) => `${C.gray}${a0} has fought no wars to a finish.`,
    youCannotPrintSWar: (/** @type {Value} */ a0) => `You cannot print ${a0}'s war records.`,
    hasNoFinishedWarNumbered: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} has no finished war numbered ${a1}. Try /clan:warhistory.`,
    printed: (/** @type {Value} */ a0) => `Printed "${a0}".`,
  },
menu: {
    tierFullClan: `${C.gray}Tier: ${C.aqua}Full clan`,
    roleFor: (/** @type {Value} */ a0) => `${C.aqua}Role for ${a0}`,
    removeMember: `${C.red}Remove Member`,
    removeFrom: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}Remove ${C.white}${a0}${C.gray} from ${C.aqua}${a1}${C.gray}?`,
    makeTheOf: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}Make ${C.white}${a0}${C.gray} the ${LEADER_ROLE} of ${C.aqua}${a1}${C.gray}?\n\n`,
    becomesAnOrdinaryMember: (/** @type {Value} */ a0) => `${C.darkGray}${a0} becomes an ordinary member.`,
    transferLeadership2: `${C.gold}Transfer Leadership`,
    leaveClan2: `${C.red}Leave Clan`,
    permanentlyDeleteAndRemoveAll: (/** @type {Value} */ a0) => `${C.gray}Permanently delete ${C.aqua}${a0}${C.gray} and remove all `,
    memberSThisCannotBe: (/** @type {Value} */ a0) => `${a0} member(s)?\n\n${C.darkGray}This cannot be undone.`,
    disbandClan2: `${C.red}Disband Clan`,
    offlinePlayersCanBeInvited: `${C.gray}Offline players can be invited; they will see it when they next join.`,
    deleteTheRole: (/** @type {Value} */ a0) => `${C.gray}Delete the role ${C.white}${a0}${C.gray}?\n\n`,
    membersHoldingItWillSimply: `${C.darkGray}Members holding it will simply have no role.`,
    deleteRole: `${C.red}Delete Role`,
    managesClans: `manages clans`,
    noClanAccess: `no clan access`,
    deleteTheStaffRoleAnd: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${C.gray}Delete the staff role ${a0}${a1}${C.gray} and un-assign ${a2} player(s)?`,
    deleteStaffRole: `${C.red}Delete Staff Role`,
    createStaffRole: `${C.green}Create Staff Role`,
    assignStaffRole: `${C.aqua}Assign Staff Role`,
    promotionFromOutpostToFull: `${C.gray}Promotion from outpost to full clan\n`,
    aNewClan: `${C.gray}A new clan\n`,
    denyRequest: `${C.red}Deny Request`,
    nameIsNotAppropriate: `Name is not appropriate`,
    sigilSettings: `${C.red}Sigil Settings`,
    leadershipOfPassesToIts: (/** @type {Value} */ a0) => `${C.yellow}Leadership of ${a0} passes to its longest-serving member.`,
    theyWillBeRemovedFrom: (/** @type {Value} */ a0) => `${C.gray}They will be removed from ${a0}.`,
    theirStaffRoleWillBe: `${C.gray}Their staff role will be cleared.`,
    theirClanRequestWillBe: `${C.gray}Their clan request will be dropped.`,
    allInvitesTheySentOr: `${C.gray}All invites they sent or received will be withdrawn.`,
    removeFromTheClanSystem: (/** @type {Value} */ a0) => `${C.gray}Remove ${C.white}${a0}${C.gray} from the clan system entirely?\n\n`,
    thisDoesNotBanThem: `${C.darkGray}This does not ban them — do that on your server or platform first. `,
    ifTheyRejoinTheyStart: `If they rejoin, they start over as a new player.`,
    purgePlayer: `${C.red}Purge Player`,
    removesAPlayerFromThe: `${C.gray}Removes a player from the clan system entirely.\n`,
    useAfterBanningThemOn: `${C.darkGray}Use after banning them on your server or platform — bans `,
    themselvesAreInvisibleToAdd: `themselves are invisible to add-ons.`,
    isAnOutpostOutpostsCannot2: (/** @type {Value} */ a0) => `${C.gray}${a0} is an ${C.gray}outpost${C.gray}. Outposts cannot go to war.`,
    activeWarSDeclarationS: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}${a0} active war(s), ${a1} declaration(s) awaiting your answer.`,
    declareWarOn: (/** @type {Value} */ a0) => `${C.gray}Declare war on ${C.aqua}${a0}${C.gray}?\n\n`,
    killsBetweenYourClansWill: `${C.darkGray}Kills between your clans will be counted on the war scoreboard.`,
    declareWar2: `${C.red}Declare War`,
    aLostClan: `A lost clan`,
    yourClan: `your clan`,
    theWarHasBegun: `${C.red}The war has begun!`,
    theyHaveOfferedPeace: `\n${C.yellow}They have offered peace.`,
    yourPeaceOfferIsAwaiting: `\n${C.gray}Your peace offer is awaiting their answer.`,
    adjustKills: `${C.aqua}Adjust Kills`,
    willBeRecordedAsThe: (/** @type {Value} */ a0) => `${C.red}${a0} will be recorded as the winner.\n`,
    thisIsPermanentAndGoes: `${C.darkGray}This is permanent and goes in the war record.`,
    surrenderedWinsTheWar: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gold}${a0} surrendered. ${a1} wins the war.`,
    hasOfferedPeaceAcceptAnd: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}${a0} has offered peace. Accept, and the war ends as a draw?\n\n${a1}`,
    offerPeaceTo: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}Offer peace to ${C.white}${a0}${C.gray}?\n\n${a1}\n\n`,
    theWarEndsOnlyOnce: `${C.darkGray}The war ends only once their Leader agrees.`,
    acceptPeace: `Accept Peace`,
    offerPeace: `Offer Peace`,
    peaceHasBeenAgreedThe: `${C.gold}Peace has been agreed. The war ends in a draw.`,
    annulTheWarBetweenAnd: (/** @type {Value} */ a0) => `${C.gray}Annul the war between ${C.white}${a0}${C.gray} and `,
    noWinnerIsRecordedUse: `${C.darkGray}No winner is recorded. Use this for a war both clans have `,
    abandonedToRecordADefeat: `abandoned — to record a defeat, a Leader must surrender.`,
    annulWar: `${C.gold}Annul War`,
    theWarHasBeenAnnulled: `${C.gray}The war has been annulled by staff. No winner was recorded.`,
    youCanRequestPromotionTo: `${C.green}You can request promotion to a full clan.\n${C.darkGray}Full clans can declare war.`,
    youNeedMoreMemberS: (/** @type {Value} */ a0) => `${C.red}You need ${a0} more member(s) before you can request promotion.`,
    requestPromotion2: `${C.green}Request Promotion`,
    requestPromotion3: `Request Promotion`,
    symbolOnly: `Symbol only`,
    nameOnly: `Name only`,
    symbolAndName: `Symbol and name`,
    nametagAndChat: `Nametag and chat`,
    nametagOnly: `Nametag only`,
    chatOnly: `Chat only`,
    nametagDisplay: `${C.white}Nametag Display`,
    beforeTheClan: `Before the clan`,
    afterTheClan: `After the clan`,
    chatDisplay: `${C.white}Chat Display`,
    adminTitle: `${C.red}Admin Title`,
    peacefulRole: `${C.green}Peaceful Role`,
    selectAPlayerToGrant: `${C.gray}Select a player to grant or clear the `,
    itStacksWithAdminAnd: `${C.darkGray}It stacks with Admin and staff roles.`,
    recordPageOf: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${a0}\n\n${C.darkGray}Page ${a1} of ${a2}`,
    queueRow: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.aqua}${a0}\n${a1}`,
    queueRowPromote: (/** @type {Value} */ a0) => `${C.gray}promotion, requested by ${a0}`,
    queueRowRename: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}rename to ${a0}, by ${a1}`,
    queueRowCreate: (/** @type {Value} */ a0) => `${C.gray}new clan, requested by ${a0}`,
    warHistoryRow: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3, /** @type {Value} */ a4) => `${C.white}${a0} vs ${a1}\n${a2}${C.darkGray} ${a3}-${a4}`,
    pickerSearchHint: (/** @type {Value} */ a0) => `${C.gray}${a0} to choose from. Search, or leave it blank to page through them.`,
    pickerSearchLabel: `${C.gray}Name contains`,
    pickerSearchPlaceholder: `part of a name`,
    pickerSearchSubmit: `Search`,
    pickerNoMatch: (/** @type {Value} */ a0) => `Nothing matches "${a0}".`,
    pickerPageOf: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3) => `${a0}\n${C.darkGray}Page ${a1} of ${a2} — ${a3} in total.`,
    pickerPrevious: `${C.gray}◀ Previous page`,
    pickerNext: `${C.gray}Next page ▶`,
    reviewNoticeCreate2: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.yellow}${a0} requested the clan ${C.aqua}${a1}${C.yellow}.\n${C.gray}Review with ${C.white}/clan:requests${C.gray}.`,
    reviewNoticePromote2: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.yellow}${a0} asked to promote ${C.aqua}${a1}${C.yellow} to a full clan.\n${C.gray}Review with ${C.white}/clan:requests${C.gray}.`,
    reviewNoticeRename2: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${C.yellow}${a0} asked to rename ${C.aqua}${a1}${C.yellow} to ${C.aqua}${a2}${C.yellow}.\n${C.gray}Review with ${C.white}/clan:requests${C.gray}.`,
    staffRoleDetailBody: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3, /** @type {Value} */ a4) => `${C.gray}Chat tag: ${a0}\n${C.gray}Clan management: ${C.white}${a1}\n${C.gray}Priority: ${C.white}${a2}\n${C.gray}Held by: ${C.white}${a3} player(s)${a4}`,
    yes: `yes`,
    no: `no`,
    builtInRoleCannotBeDeleted: `\n${C.darkGray}Built-in role; cannot be deleted.`,
    requestedByStatus: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${a0}${C.gray}Requested by ${C.white}${a1}\n${C.gray}Status: ${a2}`,
    yourRequestForTheClan: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.red}Your request for the clan ${C.aqua}${a0}${C.red} was denied.${a1}`,
    reasonGiven: (/** @type {Value} */ a0) => `\n${C.gray}Reason: ${C.white}${a0}`,
    chooseAClanToDeclare: (/** @type {Value} */ a0) => `${C.gray}Choose a clan to declare war on.\n${a0}`,
    theirLeaderMustAccept: `${C.darkGray}Their Leader must accept before the war begins.`,
    theWarBeginsImmediately: `${C.darkGray}The war begins immediately.`,
    youAreInAs: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}You are in ${C.aqua}${a0}${C.gray} as ${C.white}${a1}${C.gray}.`,
    youAreNotInA2: `${C.gray}You are not in a clan.`,
    invitesPending: (/** @type {Value} */ a0) => `${C.yellow}Invites
${C.gray}${a0} pending`,
    invitesNonePending: `${C.gray}Invites
${C.darkGray}none pending`,
    warMapWarS: (/** @type {Value} */ a0) => `${C.red}War Map
${C.gray}${a0} war(s)`,
    warMapDeclareAndTrack: `${C.red}War Map
${C.gray}declare and track wars`,
    clanRequestsAwaitingReview: (/** @type {Value} */ a0) => `${C.yellow}Clan Requests
${C.gray}${a0} awaiting review`,
    clanRequestsQueueIsEmpty: `${C.gray}Clan Requests
${C.darkGray}queue is empty`,
    activeWarsInProgress: (/** @type {Value} */ a0) => `${C.gold}Active Wars
${C.gray}${a0} in progress`,
    activeWarsNone: `${C.gray}Active Wars
${C.darkGray}none`,
    rosterPlayerS: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${a0}${a1} Roster
${C.gray}${a2} player(s)`,
    request: `Request`,
    create: `Create`,
    requestedTheClanAnAdmin2: (/** @type {Value} */ a0) => `${C.yellow}Requested the clan ${C.aqua}${a0}${C.yellow}.
${C.gray}An admin will review it. You will be told either way.`,
    anAdminReviewsTheNew: `${C.darkGray}An admin reviews the new name before it takes effect.`,
    theChangeTakesEffectImmediately: `${C.darkGray}The change takes effect immediately.`,
    rename: `Rename`,
    membersLeaderYourRole: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3, /** @type {Value} */ a4) => `${a0}
${C.gray}Members: ${C.white}${a1}${C.gray}/${a2}
${C.gray}Leader: ${C.white}${a3}
${C.gray}Your role: ${C.white}${a4}`,
    clanRoleStatus: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${C.gray}Clan: ${C.aqua}${a0}
${C.gray}Role: ${C.white}${a1}
${C.gray}Status: ${a2}`,
    invitedYouToJoinOpen: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.yellow}${a0} invited you to join ${C.aqua}${a1}${C.yellow}.
${C.gray}Open ${C.white}/clan:menu${C.gray} to respond.`,
    rolesAreOptionalLabelsFor: `${C.gray}Roles are optional labels for your members. ${C.darkGray}"${LEADER_ROLE}" is always yours and cannot be assigned.`,
    memberS4: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${C.aqua}${a0}
${C.gray}${a1} member(s) · ${a2}`,
    leaderMembers: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}Leader: ${C.white}${a0}
${C.gray}Members: ${C.white}${a1}`,
    staffRolesAreSeparateFrom: `${C.gray}Staff roles are separate from clan roles and never grant admin.
${C.darkGray}Admin is operator status and cannot be assigned here.`,
    assignStacksWithAnySystem: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0}Assign ${a1}
${C.gray}stacks with any system role`,
    deleteBuiltIn: `${C.darkGray}Delete (built-in)`,
    delete: `${C.red}Delete`,
    save2: `Save`,
    saved: (/** @type {Value} */ a0) => `Saved "${a0}".`,
    created: (/** @type {Value} */ a0) => `Created "${a0}".`,
    isNow2: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} is now ${a1}.`,
    clearedSStaffRole: (/** @type {Value} */ a0) => `Cleared ${a0}'s staff role.`,
    yourOutpostWasApprovedYou: (/** @type {Value} */ a0) => `${C.green}Your ${C.gray}outpost ${C.aqua}${a0}${C.green} was approved. You are its ${LEADER_ROLE}.`,
    warRecordsFinishedWarS: (/** @type {Value} */ a0) => `${C.gold}War Records
${C.gray}${a0} finished war(s)`,
    warRecordsNoneYet: `${C.gray}War Records
${C.darkGray}none yet`,
    hasDeclaredWarOnAnswer: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.red}${a0} has declared war on ${a1}.
${C.gray}Answer at a War Map, or with ${C.white}/clan:war${C.gray}.`,
    hasDeclaredWarOnAccepting: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}${a0} has declared war on ${C.aqua}${a1}${C.gray}.

${C.darkGray}Accepting begins the war and starts the kill count.`,
    acceptPeaceEndsAsA: `${C.green}Accept Peace
${C.gray}ends as a draw`,
    withdrawPeaceOffer: `${C.gray}Withdraw Peace Offer`,
    offerPeaceTheyMustAgree: `${C.green}Offer Peace
${C.gray}they must agree`,
    nowHasKillSTotals2: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3) => `${a0} now has ${a1} kill(s); ${a2} totals ${a3}.`,
    hasRequestedPromotionToA: (/** @type {Value} */ a0) => `${C.yellow}${a0} has requested promotion to a full clan.
${C.gray}Review with ${C.white}/clan:requests${C.gray}.`,
    clearedFrom: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Cleared ${a0} from ${a1}.`,
    youHaveBeenGivenThe: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0}You have been given the ${a1} role.`,
    yourRoleWasRemoved: (/** @type {Value} */ a0) => `${C.gray}Your ${a0} role was removed.`,
    roster: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2, /** @type {Value} */ a3) => `${a0}${a1}${C.gray} (${a2}):
${a3}`,
    thatMenuCouldNotBe: `That menu could not be opened.`,
    cancel: `${C.gray}Cancel`,
    playersSearchOrLeaveBlank: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}${a0} players. Search, or leave blank for the first ${a1}.`,
    nameContains: `${C.gray}Name contains`,
    search: `Search`,
    noPlayerMatches: (/** @type {Value} */ a0) => `No player matches "${a0}".`,
    clans: `${C.aqua}Clans`,
    myClan: (/** @type {Value} */ a0) => `${C.aqua}My Clan
${C.gray}${a0}`,
    createAClan: `${C.green}Create a Clan`,
    browseClans: `${C.white}Browse Clans`,
    manageClansStaff: `${C.gold}Manage Clans
${C.gray}staff`,
    staffRolesAdmin: `${C.red}Staff Roles
${C.gray}admin`,
    settingsAdmin: `${C.red}Settings
${C.gray}admin`,
    displaySettingsAdmin: `${C.aqua}Display Settings
${C.gray}admin`,
    adminTools: `${C.red}Admin
${C.gray}clans, wars, requests, players`,
    adminToolsWaiting: (/** @type {Value} */ a0) => `${C.red}Admin
${C.gray}${a0} awaiting review`,
    adminToolsTitle: `${C.red}Admin`,
    adminToolsBody: `${C.gray}Acting on clans, wars and players. What you can change here happens now, to somebody in particular.`,
    systemSettings: `${C.red}System Settings
${C.gray}rules, display, staff roles`,
    systemSettingsTitle: `${C.red}System Settings`,
    systemSettingsBody: `${C.gray}Rules that apply to everybody, and how the add-on looks. Admins only.`,
    createForAPlayerAdmin: `${C.green}Create a Clan for a Player
${C.gray}admin`,
    createForATitle: `${C.green}Create a Clan for a Player`,
    createForABody: `${C.gray}Choose the player who will own it. It starts as an outpost and is promoted the same way any other clan is.`,
    createForANameLabel: (/** @type {Value} */ a0) => `${C.gray}Clan name for ${C.white}${a0}`,
    purgeAPlayerAdmin: `${C.red}Purge a Player
${C.gray}admin`,
    clanNameCharacters: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}Clan name
${C.darkGray}${a0}-${a1} characters`,
    clanCreatedYouAreIts: (/** @type {Value} */ a0) => `Clan "${a0}" created. You are its ${LEADER_ROLE}.`,
    newName: `${C.gray}New name`,
    isNow: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} is now ${a1}.`,
    requestedTheNameAwaitingReview: (/** @type {Value} */ a0) => `${C.yellow}Requested the name ${C.aqua}${a0}${C.yellow}. Awaiting review.`,
    membersViewAndManage: `${C.white}Members
${C.gray}view and manage`,
    requestPromotionBecomeAFull: `${C.green}Request Promotion
${C.gray}become a full clan`,
    renameClan: `${C.aqua}Rename Clan`,
    clanColour: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.aqua}Clan Colour
${a0}${a1}`,
    clanColourTitle: `${C.aqua}Clan Colour`,
    clanColourBody: `${C.gray}The colour this clan's name is drawn in, on every member's nametag and in chat. One choice for the whole clan — members cannot set their own.`,
    clanColourPick: `${C.gray}Colour`,
    symbolKeepCurrent: (/** @type {Value} */ a0) => `${a0}  (keep the current one)`,
    clanColourDefault: `(the add-on default)`,
    clanColourUsingDefault: `${C.gray}using the default`,
    clanColourUpdated: `Clan colour updated.`,
    notClanLeaderColour: `Only the Leader can set the clan colour.`,
    inviteAPlayer: `${C.green}Invite a Player`,
    clanRolesDefined: (/** @type {Value} */ a0) => `${C.aqua}Clan Roles
${C.gray}${a0} defined`,
    transferLeadership: `${C.gold}Transfer Leadership`,
    disbandClan: `${C.red}Disband Clan`,
    leaveClan: `${C.red}Leave Clan`,
    members: (/** @type {Value} */ a0) => `${C.aqua}${a0} — Members`,
    memberSSelectOneTo: (/** @type {Value} */ a0) => `${C.gray}${a0} member(s). Select one to manage.`,
    thatMemberIsNoLonger: `That member is no longer in the clan.`,
    setRole: `${C.aqua}Set Role`,
    make: `${C.gold}Make ${LEADER_ROLE}`,
    removeFromClan: `${C.red}Remove from Clan`,
    back: `${C.gray}Back`,
    youCannotChangeRolesIn: `You cannot change roles in that clan.`,
    existingRoles: `${C.gray}Existing roles`,
    orANewRoleName: `${C.gray}Or a new role name`,
    apply: `Apply`,
    clearedSRole: (/** @type {Value} */ a0) => `Cleared ${a0}'s role.`,
    yourRoleInWasCleared: (/** @type {Value} */ a0) => `${C.gray}Your role in ${a0} was cleared.`,
    youAreNowIn: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.green}You are now ${a0} in ${a1}.`,
    youCannotRemoveMembersFrom: `You cannot remove members from that clan.`,
    removedFrom: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Removed ${a0} from ${a1}.`,
    youWereRemovedFrom: (/** @type {Value} */ a0) => `${C.red}You were removed from ${a0}.`,
    wasRemovedFromTheClan: (/** @type {Value} */ a0) => `${C.gray}${a0} was removed from the clan.`,
    youCannotChangeLeadershipOf: `You cannot change leadership of that clan.`,
    nowLeads: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} now leads ${a1}.`,
    isNowTheOf: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.yellow}${a0} is now the ${LEADER_ROLE} of ${a1}.`,
    thereIsNobodyElseIn: `There is nobody else in the clan to lead it.`,
    chooseTheNewOf: (/** @type {Value} */ a0) => `${C.gray}Choose the new ${LEADER_ROLE} of ${C.aqua}${a0}${C.gray}.`,
    youLeft: (/** @type {Value} */ a0) => `${C.gray}You left ${a0}.`,
    leftTheClan: (/** @type {Value} */ a0) => `${C.gray}${a0} left the clan.`,
    youCannotDisbandThatClan: `You cannot disband that clan.`,
    wasDisbanded: (/** @type {Value} */ a0) => `${C.red}${a0} was disbanded.`,
    disbanded: (/** @type {Value} */ a0) => `Disbanded ${a0}.`,
    nobodyIsAvailableToInvite: `Nobody is available to invite — everyone is already in a clan or invited.`,
    invitedTo: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Invited ${a0} to ${a1}.`,
    youHaveNoPendingClan: `${C.gray}You have no pending clan invites.`,
    clanInvites: `${C.yellow}Clan Invites`,
    youHavePendingInviteS: (/** @type {Value} */ a0) => `${C.gray}You have ${a0} pending invite(s).`,
    from: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.aqua}${a0}
${C.gray}from ${a1}`,
    invitedYouToJoin: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}${a0} invited you to join ${C.aqua}${a1}${C.gray}.`,
    accept: `${C.green}Accept`,
    decline: `${C.red}Decline`,
    decideLater: `${C.gray}Decide later`,
    youJoined: (/** @type {Value} */ a0) => `You joined ${a0}.`,
    joinedTheClan: (/** @type {Value} */ a0) => `${C.green}${a0} joined the clan.`,
    declinedTheInviteFrom: (/** @type {Value} */ a0) => `${C.gray}Declined the invite from ${a0}.`,
    declinedYourInviteTo: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}${a0} declined your invite to ${a1}.`,
    clanRoles: `${C.aqua}Clan Roles`,
    addARole: `${C.green}Add a Role`,
    memberS: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.white}${a0}
${C.gray}${a1} member(s)`,
    roleName: `${C.gray}Role name`,
    add: `Add`,
    addedTheRole: (/** @type {Value} */ a0) => `Added the role "${a0}".`,
    deleted: (/** @type {Value} */ a0) => `Deleted "${a0}".`,
    noClansExistYet: `${C.gray}No clans exist yet.`,
    clans2: `${C.white}Clans`,
    clanS: (/** @type {Value} */ a0) => `${C.gray}${a0} clan(s).`,
    manageClans: `${C.gold}Manage Clans`,
    selectAClanToManage: `${C.gray}Select a clan to manage its members.`,
    membersRemoveSetRoleMake: `${C.white}Members
${C.gray}remove, set role, make ${LEADER_ROLE}`,
    warRecordsPrintAPast: `${C.gold}War Records
${C.gray}print a past war`,
    staffRoles: `${C.red}Staff Roles`,
    createARole: `${C.green}Create a Role`,
    assignToAPlayer: `${C.aqua}Assign to a Player`,
    edit: `${C.aqua}Edit`,
    name: `${C.gray}Name`,
    chatTag: `${C.gray}Chat tag`,
    colour: `${C.gray}Colour`,
    showAs: `${C.gray}Show as`,
    mayManageAnyClan: `${C.gray}May manage any clan`,
    priority: `${C.gray}Priority`,
    noPlayersOnRecordYet: `${C.gray}No players on record yet.`,
    staffRole: `${C.gray}Staff role`,
    youWereGivenTheStaff: (/** @type {Value} */ a0) => `${C.green}You were given the ${a0} staff role.`,
    yourStaffRoleWasRemoved: `${C.gray}Your staff role was removed.`,
    noClanRequestsAreWaiting: `${C.gray}No clan requests are waiting.`,
    clanRequests: `${C.yellow}Clan Requests`,
    requestSAwaitingReview: (/** @type {Value} */ a0) => `${C.gray}${a0} request(s) awaiting review.`,
    thatRequestHasAlreadyBeen: `That request has already been handled.`,
    youCannotReviewThatKind: `You cannot review that kind of request.`,
    approve: `${C.green}Approve`,
    deny: `${C.red}Deny`,
    yourClanIsNowCalled: (/** @type {Value} */ a0) => `${C.aqua}Your clan is now called ${a0}.`,
    isNowAFullClan: (/** @type {Value} */ a0) => `${a0} is now a full clan.`,
    hasBeenPromotedToA: (/** @type {Value} */ a0) => `${C.gold}${a0} has been promoted to a full clan. You can now go to war.`,
    approvedFor: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `Approved ${a0} for ${a1}.`,
    reasonOptional: `${C.gray}Reason (optional)`,
    deny2: `Deny`,
    deniedTheRequestFor: (/** @type {Value} */ a0) => `${C.gray}Denied the request for ${a0}.`,
    clanCreation: `${C.gray}Clan creation`,
    requireAdminApprovalToCreate: `${C.white}Require admin approval to create a clan`,
    clanManagingStaffRolesMay: `${C.white}Clan-managing staff roles may approve`,
    outposts: `${C.gray}Outposts`,
    staffRolesMayApprovePromotions: `${C.white}Staff roles may approve promotions`,
    membersNeededToRequestPromotion: `${C.white}Members needed to request promotion`,
    wars: `${C.gray}Wars`,
    declarationsMustBeAccepted: `${C.white}Declarations must be accepted`,
    staffRolesMayAdjustWar: `${C.white}Staff roles may adjust war kills`,
    staffRolesMayPrintAny: `${C.white}Staff roles may print any war record`,
    maxActiveWarsPerClan: `${C.white}Max active wars per clan (0 = unlimited)`,
    chatNotifications: `${C.gray}Chat notifications`,
    enableNotifications: `${C.white}Enable notifications`,
    clanCreated: `${C.gray}  Clan created`,
    memberJoined: `${C.gray}  Member joined`,
    memberLeft: `${C.gray}  Member left`,
    clanDisbanded: `${C.gray}  Clan disbanded`,
    outpostPromoted: `${C.gray}  Outpost promoted`,
    warDeclared: `${C.gray}  War declared`,
    warEnded: `${C.gray}  War ended`,
    adminStatus: `${C.gray}Admin status`,
    reCheckOperatorStatusEvery: `${C.white}Re-check operator status every (seconds)`,
    save: `Save`,
    settingsSaved: `Settings saved.`,
    purgedFromTheClanSystem: (/** @type {Value} */ a0) => `Purged ${a0} from the clan system.`,
    warMap: `${C.red}War Map`,
    declareWar: `${C.red}Declare War`,
    answerDeclarationsWaiting: (/** @type {Value} */ a0) => `${C.yellow}Answer Declarations
${C.gray}${a0} waiting`,
    withdrawDeclarationUnanswered: (/** @type {Value} */ a0) => `${C.gray}Withdraw Declaration
${C.darkGray}${a0} unanswered`,
    warStandingsAllActiveWars: `${C.white}War Standings
${C.gray}all active wars`,
    ourWarsEndAWar: `${C.gold}Our Wars
${C.gray}end a war, adjust kills`,
    thereIsNoClanYou: `There is no clan you can declare on — all are outposts, or already at war with you.`,
    memberS2: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.aqua}${a0}
${C.gray}${a1} member(s)`,
    warDeclaredOnAwaitingTheir: (/** @type {Value} */ a0) => `War declared on ${a0}. Awaiting their answer.`,
    youAreNowAtWar: (/** @type {Value} */ a0) => `You are now at war with ${a0}.`,
    hasDeclaredWarOn: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.red}${a0} has declared war on ${a1}!`,
    noDeclarationsAreAwaitingYour: `${C.gray}No declarations are awaiting your answer.`,
    declarations: `${C.yellow}Declarations`,
    clanSHaveDeclaredWar: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.gray}${a0} clan(s) have declared war on ${a1}.`,
    declaredWar: (/** @type {Value} */ a0) => `${C.red}${a0}
${C.gray}declared war`,
    thatDeclarationIsNoLonger: `That declaration is no longer waiting.`,
    acceptTheWar: `${C.red}Accept the War`,
    refuse: `${C.green}Refuse`,
    theWarWithHasBegun: (/** @type {Value} */ a0) => `The war with ${a0} has begun.`,
    youRefusedTheDeclaration: `${C.gray}You refused the declaration.`,
    refusedYourDeclarationOfWar: (/** @type {Value} */ a0) => `${C.gray}${a0} refused your declaration of war.`,
    noWarsAreBeingFought: `${C.gray}No wars are being fought.`,
    warStandings: `${C.red}War Standings`,
    close: `${C.gray}Close`,
    yourClanIsNotIn: `${C.gray}Your clan is not in any war.`,
    ourWars: `${C.gold}Our Wars`,
    selectAWar: `${C.gray}Select a war.`,
    thatWarIsOver: `That war is over.`,
    war: (/** @type {Value} */ a0) => `${C.gold}${a0} War`,
    state: (/** @type {Value} */ a0, /** @type {Value} */ a1, /** @type {Value} */ a2) => `${a0}
${C.gray}State: ${C.white}${a1}${a2}`,
    adjustKillsStaff: `${C.aqua}Adjust Kills
${C.gray}staff`,
    surrenderTheyAreRecordedAs: `${C.red}Surrender
${C.gray}they are recorded as the winner`,
    annulWarStaffNoWinner: `${C.gold}Annul War
${C.gray}staff — no winner`,
    clan: `${C.gray}Clan`,
    changeBy: `${C.gray}Change by`,
    namingAMemberPutsThe: `${C.darkGray}Naming a member puts the change on their own line.`,
    creditTo: `${C.gray}Credit to`,
    totalsAsAnAdjustment: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${a0} totals ${a1}, as an adjustment.`,
    youSurrenderedWon: (/** @type {Value} */ a0) => `${C.gray}You surrendered. ${a0} won.`,
    peaceOfferedTo: (/** @type {Value} */ a0) => `Peace offered to ${a0}.`,
    hasOfferedPeaceAnswerAt: (/** @type {Value} */ a0) => `${C.yellow}${a0} has offered peace. Answer at a War Map.`,
    peaceAgreedTheWarIs: `Peace agreed. The war is over.`,
    youCannotAnnulWars: `You cannot annul wars.`,
    theWarWasAnnulled: `The war was annulled.`,
    peaceOfferWithdrawn: `${C.gray}Peace offer withdrawn.`,
    youHaveNoUnansweredDeclarations: `${C.gray}You have no unanswered declarations.`,
    withdrawDeclaration: `${C.gray}Withdraw Declaration`,
    theseClansHaveNotAnswered: `${C.gray}These clans have not answered yet. Withdrawing leaves no record.`,
    withdrewTheDeclarationAgainst: (/** @type {Value} */ a0) => `${C.gray}Withdrew the declaration against ${a0}.`,
    withdrewItsDeclarationOfWar: (/** @type {Value} */ a0) => `${C.gray}${a0} withdrew its declaration of war.`,
    youDoNotHaveWar: `You do not have war-management access.`,
    activeWars: `${C.gold}Active Wars`,
    warSInProgress: (/** @type {Value} */ a0) => `${C.gray}${a0} war(s) in progress.`,
    thatWarIsNoLonger: `That war is no longer on record.`,
    warRecords: `${C.gold}War Records`,
    chooseAClanWhoseWar: `${C.gray}Choose a clan whose war history to read.`,
    finishedWarS: (/** @type {Value} */ a0, /** @type {Value} */ a1) => `${C.aqua}${a0}
${C.gray}${a1} finished war(s)`,
    hasFoughtNoWarsTo: (/** @type {Value} */ a0) => `${C.gray}${a0} has fought no wars to a finish.`,
    wars2: (/** @type {Value} */ a0) => `${C.gold}${a0} — Wars`,
    finishedWarSSelectOne: (/** @type {Value} */ a0) => `${C.gray}${a0} finished war(s). Select one to print its record.`,
    youCannotPrintThatClan: `You cannot print that clan’s war records.`,
    printed: (/** @type {Value} */ a0) => `Printed "${a0}".`,
    requestPromotion: `${C.green}Request Promotion`,
    requestedPromotionForAwaitingReview: (/** @type {Value} */ a0) => `${C.yellow}Requested promotion for ${C.aqua}${a0}${C.yellow}. Awaiting review.`,
    displaySettings: `${C.aqua}Display Settings`,
    howClanAndSystemIdentity: `${C.gray}How clan and system identity is drawn.`,
    nametagsRoleOrderBrackets: `${C.white}Nametags
${C.gray}role, order, brackets`,
    chatRoleOrder: `${C.white}Chat
${C.gray}role, order`,
    adminTitleSymbolNameColour: `${C.red}Admin Title
${C.gray}symbol, name, colour`,
    peacefulRoleSymbolVisibilityOrder: `${C.green}Peaceful Role
${C.gray}symbol, visibility, order`,
    coloursClanRoleOutpost: `${C.aqua}Default Colours
${C.gray}clan, role, outpost`,
    coloursAreDefaultsBody: `${C.gray}Defaults, used by every clan whose Leader has not chosen a colour of its own.`,
    showTheClanRole: `${C.white}Show the clan role`,
    rolePosition: `${C.gray}Role position`,
    clanBrackets: `${C.gray}Clan brackets`,
    clanBracketColour: `${C.gray}Clan bracket colour`,
    roleBracketColour: `${C.gray}Role bracket colour`,
    chatClanBrackets: `${C.gray}Clan tag brackets`,
    chatClanBracketColour: `${C.gray}Clan tag bracket colour`,
    roleBrackets: `${C.gray}Role brackets`,
    lowerNumbersAreDrawnFirst: `${C.darkGray}Lower numbers are drawn first, before the player name.`,
    systemTitleOrder: `${C.gray}System title order`,
    peacefulOrder: `${C.gray}Peaceful order`,
    nametagDisplayUpdated: `Nametag display updated.`,
    showTheClanRoleIn: `${C.white}Show the clan role in chat`,
    lowerNumbersAreDrawnFirst2: `${C.darkGray}Lower numbers are drawn first. The player's name has an order of its own, so anything numbered above it is drawn after the name instead of before it.`,
    playerNameOrder: `${C.gray}Player name order`,
    clanTagOrder: `${C.gray}Clan tag order`,
    chatDisplayUpdated: `Chat display updated.`,
    adminIsOperatorStatusAnd: `${C.darkGray}Admin is operator status and cannot be assigned here.`,
    symbol: `${C.gray}Symbol`,
    adminTitleUpdated: `Admin title updated.`,
    visibleIn: `${C.gray}Visible in`,
    clanManagingStaffRolesMay2: `${C.white}Clan-managing staff roles may grant it`,
    peacefulRoleUpdated: `Peaceful role updated.`,
    clanName: `${C.gray}Default clan name`,
    clanRole: `${C.gray}Clan role`,
    outpostName: `${C.gray}Default outpost name`,
    coloursUpdated: `Colours updated.`,
    youCannotViewThePeaceful: `You cannot view the Peaceful roster.`,
    nobodyHoldsTheRole: (/** @type {Value} */ a0) => `${C.gray}Nobody holds the ${a0} role.`,
  },
};
