// Generates the two pack icons.
//
//   node tools/make-icons.mjs
//
// Like the textures, these are drawn in code rather than committed as opaque
// binaries, so the art can be reviewed in a diff and regenerated by changing a
// number.
//
//   clan_bp/pack_icon.png   128x128  crimson shield, crossed swords, "SIGIL"
//   clan_rp/pack_icon.png   128x128  the same mark in steel blue, "RESOURCES"
//
// Both are the same emblem in two palettes: they need to read as a pair in the
// pack list, where they always appear together, while still being told apart at
// a glance. The wordmark carries the name because an emblem alone would not.

import { writePng, canvas, set, get, disc, rng } from './pixels.mjs';

const S = 128;

// ── A 5x7 pixel font ──────────────────────────────────────────────────────
//
// Only the letters the two icons actually spell. Drawing a glyph that is not
// here throws rather than silently leaving a gap.

const FONT = {
  S: ['.###.', '#...#', '#....', '.###.', '....#', '#...#', '.###.'],
  I: ['#####', '..#..', '..#..', '..#..', '..#..', '..#..', '#####'],
  G: ['.###.', '#...#', '#....', '#.###', '#...#', '#...#', '.###.'],
  L: ['#....', '#....', '#....', '#....', '#....', '#....', '#####'],
  R: ['####.', '#...#', '#...#', '####.', '#..#.', '#...#', '#...#'],
  E: ['#####', '#....', '#....', '####.', '#....', '#....', '#####'],
  O: ['.###.', '#...#', '#...#', '#...#', '#...#', '#...#', '.###.'],
  U: ['#...#', '#...#', '#...#', '#...#', '#...#', '#...#', '.###.'],
  C: ['.###.', '#...#', '#....', '#....', '#....', '#...#', '.###.'],
};

/** The gap between letters. A full blank column reads as too loose when the
 * wordmark is set large, and pushes it into the frame. */
function gap(scale) {
  return Math.max(1, Math.round(scale / 2));
}

/** Width in pixels of `text` drawn at `scale`, including inter-letter gaps. */
function textWidth(text, scale) {
  return text.length * (5 * scale + gap(scale)) - gap(scale);
}

/**
 * Draws `text` with its top-left at (x, y). Each font pixel becomes a
 * `scale`x`scale` block, so the letterforms stay crisp instead of being
 * resampled.
 */
function drawText(c, text, x, y, scale, rgb) {
  let cx = x;
  for (const ch of text) {
    const glyph = FONT[ch];
    if (!glyph) throw new Error(`no glyph for ${JSON.stringify(ch)}`);
    glyph.forEach((row, gy) => {
      [...row].forEach((cell, gx) => {
        if (cell !== '#') return;
        for (let dy = 0; dy < scale; dy++) {
          for (let dx = 0; dx < scale; dx++) {
            set(c, cx + gx * scale + dx, y + gy * scale + dy, rgb);
          }
        }
      });
    });
    cx += 5 * scale + gap(scale);
  }
}

/** Draws text with a hard drop shadow, so it survives a dark background. */
function drawTextShadowed(c, text, x, y, scale, rgb, shadow) {
  const off = Math.max(1, Math.round(scale / 2));
  drawText(c, text, x + off, y + off, scale, shadow);
  drawText(c, text, x, y, scale, rgb);
}

/** Draws `text` centred horizontally on the icon. */
function drawTextCentred(c, text, y, scale, rgb, shadow) {
  drawTextShadowed(c, text, Math.round((S - textWidth(text, scale)) / 2), y, scale, rgb, shadow);
}

// ── Shapes ────────────────────────────────────────────────────────────────

/**
 * A stroke of constant width, drawn as overlapping discs. Used for the sword
 * blades and grips, where a one-pixel Bresenham line would be far too thin.
 */
function stroke(c, x0, y0, x1, y1, rgb, width) {
  const steps = Math.ceil(Math.hypot(x1 - x0, y1 - y0) * 2);
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    disc(c, x0 + (x1 - x0) * t, y0 + (y1 - y0) * t, width / 2, rgb);
  }
}

/**
 * The half-width of a heraldic shield at vertical position `t` (0 at the top
 * edge, 1 at the point).
 *
 * Straight sides down to 55%, then an elliptical taper to the point. The top
 * corners are eased in slightly so they do not read as a hard rectangle.
 */
function shieldHalfWidth(t, w) {
  if (t < 0) return 0;
  if (t <= 0.55) {
    const corner = t < 0.05 ? 0.72 + (t / 0.05) * 0.28 : 1;
    return w * corner;
  }
  const k = (t - 0.55) / 0.45;
  return w * Math.sqrt(Math.max(0, 1 - k * k));
}

/** Fills a shield spanning `top`..`bottom`, centred on `cx`. */
function shield(c, cx, top, bottom, w, rgb) {
  for (let y = Math.floor(top); y <= Math.ceil(bottom); y++) {
    const hw = shieldHalfWidth((y - top) / (bottom - top), w);
    for (let x = Math.round(cx - hw); x <= Math.round(cx + hw); x++) set(c, x, y, rgb);
  }
}

/**
 * One sword, pointing along the unit vector (dx, dy) from the crossing point.
 *
 * Drawn hilt-first so the blade sits over the grip rather than under it.
 */
function sword(c, cx, cy, dx, dy, palette) {
  const at = (t, o = 0) => [cx + dx * t - dy * o, cy + dy * t + dx * o];

  // Grip and pommel, behind the crossguard.
  stroke(c, ...at(-11), ...at(-21), palette.grip, 5);
  disc(c, ...at(-23), 3.4, palette.gold);

  // Crossguard, perpendicular to the blade.
  stroke(c, ...at(-9, -8), ...at(-9, 8), palette.gold, 4);

  // Blade, then a highlight down one edge to give it a direction of light.
  stroke(c, ...at(-9), ...at(23), palette.steel, 6);
  stroke(c, ...at(-7, -1.4), ...at(21, -1.4), palette.steelLight, 1.6);
  // The point.
  stroke(c, ...at(23), ...at(27), palette.steel, 2.4);
}

// ── The icon ──────────────────────────────────────────────────────────────

const CRIMSON = {
  bg: [20, 24, 32],
  bgEdge: [10, 12, 17],
  frame: [201, 154, 62],
  field: [142, 36, 52],
  fieldDark: [96, 22, 36],
  gold: [217, 164, 65],
  goldLight: [240, 205, 122],
  steel: [201, 210, 220],
  steelLight: [238, 244, 250],
  grip: [74, 48, 32],
  word: [232, 200, 106],
  shadow: [8, 9, 13],
};

const STEEL = {
  bg: [18, 22, 30],
  bgEdge: [9, 11, 16],
  frame: [138, 162, 184],
  field: [36, 80, 107],
  fieldDark: [22, 54, 76],
  gold: [166, 190, 210],
  goldLight: [214, 230, 242],
  steel: [196, 206, 218],
  steelLight: [236, 242, 249],
  grip: [52, 62, 76],
  word: [186, 210, 230],
  shadow: [7, 9, 13],
};

/**
 * @param {typeof CRIMSON} p palette
 * @param {string[]} words wordmark lines, largest first
 */
function makeIcon(p, words) {
  const c = canvas(S, S);
  const rand = rng(0x51617);

  // 1. Background: a vignette from the centre, plus a little grain so large
  //    flat areas do not band.
  const cx = (S - 1) / 2;
  for (let y = 0; y < S; y++) {
    for (let x = 0; x < S; x++) {
      const d = Math.hypot(x - cx, y - cx) / (S * 0.72);
      const k = Math.min(1, d * d);
      const grain = Math.round((rand() - 0.5) * 6);
      set(c, x, y, [
        Math.round(p.bg[0] + (p.bgEdge[0] - p.bg[0]) * k) + grain,
        Math.round(p.bg[1] + (p.bgEdge[1] - p.bg[1]) * k) + grain,
        Math.round(p.bg[2] + (p.bgEdge[2] - p.bg[2]) * k) + grain,
      ]);
    }
  }

  // 2. A thin frame, inset, so the icon has a defined edge against whatever
  //    the pack list draws behind it.
  for (let i = 3; i < 5; i++) {
    for (let n = 3; n < S - 3; n++) {
      set(c, n, i, p.frame);
      set(c, n, S - 1 - i, p.frame);
      set(c, i, n, p.frame);
      set(c, S - 1 - i, n, p.frame);
    }
  }

  // 3. The shield: a gold silhouette with the field laid inside it, which
  //    gives a clean border of even thickness all the way round the curve.
  const twoLine = words.length > 1;
  const top = twoLine ? 11 : 15;
  const bottom = twoLine ? 71 : 83;
  const w = twoLine ? 25 : 28;

  shield(c, cx, top + 2, bottom + 2, w, p.shadow); // dropped shadow
  shield(c, cx, top, bottom, w, p.gold);
  shield(c, cx, top + 3, bottom - 4, w - 3, p.field);

  // A darker lower half, so the shield reads as curved rather than flat.
  for (let y = Math.round(top + (bottom - top) * 0.52); y <= bottom; y++) {
    const hw = shieldHalfWidth((y - top) / (bottom - top), w - 3);
    for (let x = Math.round(cx - hw); x <= Math.round(cx + hw); x++) {
      const cur = get(c, x, y);
      if (cur[0] === p.field[0] && cur[1] === p.field[1] && cur[2] === p.field[2]) {
        set(c, x, y, p.fieldDark);
      }
    }
  }

  // 4. Crossed swords over the field.
  const sy = top + (bottom - top) * 0.44;
  const d = Math.SQRT1_2;
  sword(c, cx, sy, d, -d, p);
  sword(c, cx, sy, -d, -d, p);

  // 5. The wordmark.
  if (twoLine) {
    drawTextCentred(c, words[0], 80, 3, p.word, p.shadow);
    drawTextCentred(c, words[1], 106, 2, p.frame, p.shadow);
  } else {
    drawTextCentred(c, words[0], 91, 4, p.word, p.shadow);
  }

  return c;
}

// ── Output ────────────────────────────────────────────────────────────────

console.log('clan_bp/pack_icon.png', writePng('clan_bp/pack_icon.png', makeIcon(CRIMSON, ['SIGIL'])));
console.log(
  'clan_rp/pack_icon.png',
  writePng('clan_rp/pack_icon.png', makeIcon(STEEL, ['SIGIL', 'RESOURCES'])),
);
