// A tiny pixel-drawing surface and a PNG writer.
//
// Shared by the texture and pack-icon generators. Both draw art in code rather
// than committing opaque binaries, so the art can be reviewed in a diff and
// regenerated by changing a number. Randomness runs through a seeded generator,
// so output is identical on every run.

import zlib from 'node:zlib';
import fs from 'node:fs';
import path from 'node:path';

// ── PNG writing ───────────────────────────────────────────────────────────

const CRC = (() => {
  const t = [];
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const td = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  let c = 0xffffffff;
  for (const b of td) c = CRC[(c ^ b) & 0xff] ^ (c >>> 8);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE((c ^ 0xffffffff) >>> 0);
  return Buffer.concat([len, td, crc]);
}

export function writePng(file, canvas) {
  const { w, h, px } = canvas;
  const raw = Buffer.alloc(h * (w * 4 + 1));
  for (let y = 0; y < h; y++) {
    raw[y * (w * 4 + 1)] = 0;
    px.copy(raw, y * (w * 4 + 1) + 1, y * w * 4, (y + 1) * w * 4);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0);
  ihdr.writeUInt32BE(h, 4);
  ihdr[8] = 8;
  ihdr[9] = 6;
  const png = Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    chunk('IHDR', ihdr),
    chunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, png);
  return png.length;
}

// ── Tiny drawing surface ──────────────────────────────────────────────────

export function canvas(w, h) {
  return { w, h, px: Buffer.alloc(w * h * 4) };
}

export function set(c, x, y, rgb, a = 255) {
  if (x < 0 || y < 0 || x >= c.w || y >= c.h) return;
  const i = (y * c.w + x) * 4;
  c.px[i] = rgb[0];
  c.px[i + 1] = rgb[1];
  c.px[i + 2] = rgb[2];
  c.px[i + 3] = a;
}

export function get(c, x, y) {
  if (x < 0 || y < 0 || x >= c.w || y >= c.h) return [0, 0, 0, 0];
  const i = (y * c.w + x) * 4;
  return [c.px[i], c.px[i + 1], c.px[i + 2], c.px[i + 3]];
}

export function opaque(c, x, y) {
  return get(c, x, y)[3] > 0;
}

export function clear(c, x, y) {
  if (x < 0 || y < 0 || x >= c.w || y >= c.h) return;
  c.px[(y * c.w + x) * 4 + 3] = 0;
}

/** Darkens or lightens an existing pixel, leaving transparent ones alone. */
export function shade(c, x, y, amount) {
  if (!opaque(c, x, y)) return;
  const i = (y * c.w + x) * 4;
  for (let k = 0; k < 3; k++) {
    c.px[i + k] = Math.max(0, Math.min(255, Math.round(c.px[i + k] + amount)));
  }
}

export function line(c, x0, y0, x1, y1, rgb) {
  const dx = Math.abs(x1 - x0);
  const dy = Math.abs(y1 - y0);
  const sx = x0 < x1 ? 1 : -1;
  const sy = y0 < y1 ? 1 : -1;
  let err = dx - dy;
  let x = x0;
  let y = y0;
  for (;;) {
    set(c, x, y, rgb);
    if (x === x1 && y === y1) break;
    const e2 = 2 * err;
    if (e2 > -dy) {
      err -= dy;
      x += sx;
    }
    if (e2 < dx) {
      err += dx;
      y += sy;
    }
  }
}

export function disc(c, cx, cy, r, rgb) {
  for (let y = Math.floor(cy - r); y <= Math.ceil(cy + r); y++) {
    for (let x = Math.floor(cx - r); x <= Math.ceil(cx + r); x++) {
      if ((x - cx) ** 2 + (y - cy) ** 2 <= r * r) set(c, x, y, rgb);
    }
  }
}

export function triangle(c, p0, p1, p2, rgb) {
  const minX = Math.floor(Math.min(p0[0], p1[0], p2[0]));
  const maxX = Math.ceil(Math.max(p0[0], p1[0], p2[0]));
  const minY = Math.floor(Math.min(p0[1], p1[1], p2[1]));
  const maxY = Math.ceil(Math.max(p0[1], p1[1], p2[1]));
  const area = (a, b, p) => (b[0] - a[0]) * (p[1] - a[1]) - (b[1] - a[1]) * (p[0] - a[0]);
  for (let y = minY; y <= maxY; y++) {
    for (let x = minX; x <= maxX; x++) {
      const p = [x + 0.5, y + 0.5];
      const d0 = area(p0, p1, p);
      const d1 = area(p1, p2, p);
      const d2 = area(p2, p0, p);
      const neg = d0 < 0 || d1 < 0 || d2 < 0;
      const pos = d0 > 0 || d1 > 0 || d2 > 0;
      if (!(neg && pos)) set(c, x, y, rgb);
    }
  }
}

/** Deterministic PRNG, so every run produces the same texture. */
export function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
